# Generated by Django 4.0.1 on 2022-01-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('phone_no', models.CharField(max_length=10)),
                ('pic', models.ImageField(null=True, upload_to='portfolio')),
                ('aboutme', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('fb_address', models.CharField(default=' ', max_length=50)),
                ('insta_address', models.CharField(default=' ', max_length=50)),
                ('linkdin_id', models.CharField(default=' ', max_length=50)),
                ('github_id', models.CharField(default=' ', max_length=50)),
                ('twitter_id', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Myexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(default='Present')),
                ('post', models.CharField(max_length=100)),
                ('name_of_company', models.CharField(max_length=100)),
                ('address_of_company', models.CharField(max_length=100)),
                ('years', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Myprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=50)),
                ('language_used', models.CharField(max_length=20)),
                ('project_description', models.TextField(max_length=500)),
                ('project_image', models.ImageField(null=True, upload_to='portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Myskils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('skill_measure', models.IntegerField()),
                ('pic', models.ImageField(null=True, upload_to='portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pic', models.ImageField(null=True, upload_to='portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadcv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cv', models.FileField(upload_to='portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Workingstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_style', models.CharField(max_length=150)),
            ],
        ),
    ]
